### ISSUE TITLE
Hope to be a contributor

### ISSUE THREAD

**Issue by soulstar9792** [StarfilesFileSharing/hydrafiles#60]
Hello,

I recently came across your GitHub project and was truly impressed by the innovative concept behind it. As a senior web, blockchain, and AI engineer with eight years of experience, I would love the opportunity to contribute to your project.

Please feel free to reach out to me at your convenience. I look forward to hearing from you!

Best regards,

Joe
secondstar9792@gmail.com
https://t.me/secondstar9792

**Comment by QuixThe2nd** [comment]
Thanks for this, sent you a message.
